name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

# Release Please needs permissions to write commits and open PRs.
permissions:
  contents: write
  pull-requests: write

env:
  NODE_LTS_VERSION: 22.x

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_LTS_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test with Coverage
        run: npm run test:cov

      - name: Validate Install
        run: |
          mkdir temp-test && cd temp-test
          # Do an install from a child folder, basically faking what a consumer
          # would do. We're just installing from the local files rather than
          # NPM, to validate we get the expected essential file.
          npm install ..
          echo "Checking installation contains index.js..."
          stat ./dist/index.js || (echo "index.js appears to be missing" && exit 1)

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./artifacts/

  upload-coverage:
    name: Upload Coverage
    needs: validate
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./artifacts

      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        with:
          directory: ./artifacts/coverage
          token: ${{ secrets.CODECOV_TOKEN }}

  release-please:
    name: Release PR/Deploy
    needs: validate
    runs-on: ubuntu-24.04
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: "@dwmkerr/advanced-input-prompt"

      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup Node for Release
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_LTS_VERSION }}
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}

      - name: Build Distributable
        run: |
          npm install
          npm run build
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to NPM
        run: |
          if [ "$NODE_AUTH_TOKEN" == "" ]; then
            echo "The 'NPM_TOKEN' secret must be set to deploy to NPM"
            exit 1
          else
            echo "Publishing to NPM..."
            npm publish --access=public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}

